branches:
language: perl
perl:
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"  # IO::Tty is missing on the Travis server or cannot be installed?
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
script:
  - export PERL_USE_UNSAFE_INC=0
  - export AUTHOR_TESTING=1
  - export AUTOMATED_TESTING=1
  - export RELEASE_TESTING=1
  - export PERL_MM_USE_DEFAULT=1
  - perl Makefile.PL && make test
